# Generated by Django 4.1.7 on 2023-03-07 21:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "pkg_trans",
            "0002_distribution_dependencies_distribution_generated_for_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="distribution",
            name="js_name",
            field=models.CharField(
                help_text="The canonical NPM name of this package", max_length=1000
            ),
        ),
        migrations.AlterUniqueTogether(
            name="distribution",
            unique_together={("generated_for", "js_name")},
        ),
    ]
