name: Release Python package

on:
    push:
        tags:
            - "*"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Build and publish to pypi
              uses: JRubics/poetry-publish@v1.15
              with:
                  pypi_token: ${{ secrets.PYPI_TOKEN }}
                  python_version: "3.10"
                  package_directory: "package"
